//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import <Foundation/Foundation.h>
@class NSObject,NSString,NSNumber,NSValue;

@interface STDeviceChecker : NSValue
{
	NSString* String;
	NSNumber* Number;
}
@property NSString* NameProp;
+ (void)deviceHasBeenCompromised:(NSString*) arg1 WithArg2:(NSNumber*)arg2;

@end

